apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: kyverno-placement
  namespace: open-cluster-management-global-set
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
          - {key: name, operator: In, values: ["local-cluster"]}
