apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: helmtest
placementBindingDefaults:
  name:  helmtest
policyDefaults:
  configurationPolicyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: policies
  remediationAction: enforce
  severity: medium
  standards:
    - generic
  placementPath:  
    - placement.yaml
policies:
- name: namespace
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input

















